# Generated by Django 5.1.2 on 2025-07-26 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('punto_atencion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('atendiendo', 'Atendiendo'), ('finalizado', 'Finalizado')], default='esperando', max_length=20)),
                ('prioridad', models.BooleanField(default=False)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_atencion.puntoatencion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llamada', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_atencion', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_atencion', models.DateTimeField(blank=True, null=True)),
                ('numero_turno_en_tablero', models.IntegerField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_operador', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
