# Generated by Django 5.1.2 on 2025-07-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('esperando', 'Esperando'), ('atendiendo', 'Atendiendo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='esperando', max_length=20),
        ),
    ]
