# Generated by Django 5.1.2 on 2025-08-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
